// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Sat Jan 14 19:19:23 CET 2023
// generated file: do not modify
package com.xlend.orm;

import com.xlend.orm.dbobject.DbObject;
import com.xlend.orm.dbobject.ForeignKeyViolationException;
import com.xlend.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Mats_mattype extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer mattypeID = null;
    private String name = null;

    public Mats_mattype(Connection connection) {
        super(connection, "mats_mattype", "mattypeID");
        setColumnNames(new String[]{"mattypeID", "name"});
    }

    public Mats_mattype(Connection connection, Integer mattypeID, String name) {
        super(connection, "mats_mattype", "mattypeID");
        setNew(mattypeID.intValue() <= 0);
//        if (mattypeID.intValue() != 0) {
            this.mattypeID = mattypeID;
//        }
        this.name = name;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Mats_mattype mats_mattype = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT mattypeID,name FROM mats.mattype WHERE mattypeID=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                mats_mattype = new Mats_mattype(getConnection());
                mats_mattype.setMattypeID(new Integer(rs.getInt(1)));
                mats_mattype.setName(rs.getString(2));
                mats_mattype.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return mats_mattype;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO mats.mattype ("+(getMattypeID().intValue()!=0?"mattypeID,":"")+"name) values("+(getMattypeID().intValue()!=0?"?,":"")+"?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getMattypeID().intValue()!=0) {
                 ps.setObject(++n, getMattypeID());
             }
             ps.setObject(++n, getName());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getMattypeID().intValue()==0) {
             stmt = "SELECT max(mattypeID) FROM mats.mattype";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setMattypeID(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE mats.mattype " +
                    "SET name = ?" + 
                    " WHERE mattypeID = " + getMattypeID();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getName());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (Mats_item.exists(getConnection(),"mattypeID = " + getMattypeID())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: key");
        }
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM mats.mattype " +
                "WHERE mattypeID = " + getMattypeID();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setMattypeID(new Integer(-getMattypeID().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getMattypeID().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT mattypeID,name FROM mats.mattype " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Mats_mattype(con,new Integer(rs.getInt(1)),rs.getString(2)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Mats_mattype[] objects = new Mats_mattype[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Mats_mattype mats_mattype = (Mats_mattype) lst.get(i);
            objects[i] = mats_mattype;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT mattypeID FROM mats.mattype " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getMattypeID() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return mattypeID;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setMattypeID(id);
        setNew(prevIsNew);
    }

    public Integer getMattypeID() {
        return mattypeID;
    }

    public void setMattypeID(Integer mattypeID) throws ForeignKeyViolationException {
        setWasChanged(this.mattypeID != null && this.mattypeID != mattypeID);
        this.mattypeID = mattypeID;
        setNew(mattypeID.intValue() == 0);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.name != null && !this.name.equals(name));
        this.name = name;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[2];
        columnValues[0] = getMattypeID();
        columnValues[1] = getName();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setMattypeID(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setMattypeID(null);
        }
        setName(flds[1]);
    }
}
